### ISSUE TITLE
hi! error when ''catkin build ur_to_touch_haptic_teleoperation'', can you help me plz 

### ISSUE THREAD

**Issue by lw111111111** [OltanS/thesis_teleoperation_packages#3] opened 2023-10-26 12:17 UTC
Errors     << ur_to_touch_haptic_teleoperation:cmake /home/wei/catkin_ws/logs/ur_to_touch_haptic_teleoperation/build.cmake.000.log
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "omni_common" with
  any of the following names:

    omni_commonConfig.cmake
    omni_common-config.cmake

  Add the installation prefix of "omni_common" to CMAKE_PREFIX_PATH or set "omni_common_DIR" to a directory containing one of the above files.  If "omni_common" provides a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)
Failed     << ur_to_touch_haptic_teleoperation:cmake              [ Exited with code 1 ]
Failed    <<< ur_to_touch_haptic_teleoperation                    [ 5.5 seconds ]
[build] Summary: 17 of 18 packages succeeded.                                  
[build]   Ignored:   46 packages were skipped or are skiplisted.               
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 27.0 seconds total.                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by OltanS** [comment] 2023-10-30 10:30
Hi LW,

I'm not sure what the root of the problem is, but it seems to be a more general problem than a specific one to this here. 
Hope you've had some progress with it in the time it took for me to see this issue.

Since I'm not looking to support the software here, I will be closing this issue.

**Closed by OltanS** 2023-10-30 10:30 UTC
